import type { Player } from "@/types/player";

export const players: Player[] = [
  {
    name: "Raúl Rangel",
    position: "Portero",
    number: 1,
    image: "/images/players/raul-rangel.png",
    slug: "raul-rangel",
    stats: {
      appearances: 0,
      goals: 0,
      assists: 0,
      yellowCards: 0,
      redCards: 0,
      minutesPlayed: 0,
    },
  },
  {
    name: "Oscar Whalley",
    position: "Portero",
    number: 30,
    image: "/images/players/oscar-whalley.png",
    slug: "oscar-whalley",
  },
  {
    name: "Alan Mozo",
    position: "Defensa",
    number: 2,
    image: "/images/players/alan-mozo.png",
    slug: "alan-mozo",
  },
  {
    name: "Gilberto Sepúlveda",
    position: "Defensa",
    number: 3,
    image: "/images/players/gilberto-sepulveda.png",
    slug: "gilberto-sepulveda",
  },
  {
    name: "Miguel Tapias",
    position: "Defensa",
    number: 4,
    image: "/images/players/miguel-tapias.png",
    slug: "miguel-tapias",
  },
  {
    name: "Luis Olivas",
    position: "Defensa",
    number: 18,
    image: "/images/players/luis-olivas.png",
    slug: "luis-olivas",
  },
  {
    name: "José Castillo",
    position: "Defensa",
    number: 21,
    image: "/images/players/jose-castillo.png",
    slug: "jose-castillo",
  },
  {
    name: "Leonardo Sepúlveda",
    position: "Defensa",
    number: 27,
    image: "/images/players/leonardo-sepulveda.png",
    slug: "leonardo-sepulveda",
  },
  {
    name: "Raúl Martínez",
    position: "Defensa",
    number: 33,
    image: "/images/players/raul-martinez.png",
    slug: "raul-martinez",
  },
  {
    name: "Erick Gutiérrez",
    position: "Mediocampista",
    number: 15,
    image: "/images/players/erick-gutierrez.png",
    slug: "erick-gutierrez",
  },
  {
    name: "Omar Govea",
    position: "Mediocampista",
    number: 7,
    image: "/images/players/omar-govea.png",
    slug: "omar-govea",
  },
  {
    name: "Issac Brizuela",
    position: "Mediocampista",
    number: 11,
    image: "/images/players/issac-brizuela.png",
    slug: "issac-brizuela",
  },
  {
    name: "Luis Romo",
    position: "Mediocampista",
    number: 17,
    image: "/images/players/luis-romo.png",
    slug: "luis-romo",
  },
  {
    name: "Daniel Aguirre",
    position: "Mediocampista",
    number: 23,
    image: "/images/players/daniel-aguirre.png",
    slug: "daniel-aguirre",
  },
  {
    name: "Rubén González",
    position: "Mediocampista",
    number: 28,
    image: "/images/players/ruben-gonzalez.png",
    slug: "ruben-gonzalez",
  },
  {
    name: "Javier Hernández",
    position: "Delantero",
    number: 14,
    image: "/images/players/javier-hernandez.png",
    slug: "javier-hernandez",
  },
  {
    name: "Alan Pulido",
    position: "Delantero",
    number: 9,
    image: "/images/players/alan-pulido.png",
    slug: "alan-pulido",
  },
  {
    name: "Cade Cowell",
    position: "Delantero",
    number: 16,
    image: "/images/players/cade-cowell.png",
    slug: "cade-cowell",
  },
  {
    name: "Roberto Alvarado",
    position: "Delantero",
    number: 25,
    image: "/images/players/roberto-alvarado.png",
    slug: "roberto-alvarado",
  },
  {
    name: "Yael Padilla",
    position: "Delantero",
    number: 31,
    image: "/images/players/yael-padilla.png",
    slug: "yael-padilla",
  },
  {
    name: "Armando González",
    position: "Delantero",
    number: 34,
    image: "/images/players/armando-gonzalez.png",
    slug: "armando-gonzalez",
  },
  {
    name: "Teun Wilke",
    position: "Delantero",
    number: 35,
    image: "/images/players/teun-wilke.png",
    slug: "teun-wilke",
  },
];
