export const players = [
  {
    name: "Raúl Rangel",
    position: "Portero",
    number: 1,
    image: "/images/players/raul-rangel.png",
  },
  {
    name: "Oscar Whalley",
    position: "Portero",
    number: 30,
    image: "/images/players/oscar-whalley.png",
  },
  {
    name: "Alan Mozo",
    position: "Defensa",
    number: 2,
    image: "/images/players/alan-mozo.png",
  },
  {
    name: "Gilberto Sepúlveda",
    position: "Defensa",
    number: 3,
    image: "/images/players/gilberto-sepulveda.png",
  },
  {
    name: "Miguel Tapias",
    position: "Defensa",
    number: 4,
    image: "/images/players/miguel-tapias.png",
  },
  {
    name: "Luis Olivas",
    position: "Defensa",
    number: 18,
    image: "/images/players/luis-olivas.png",
  },
  {
    name: "José Castillo",
    position: "Defensa",
    number: 21,
    image: "/images/players/jose-castillo.png",
  },
  {
    name: "Leonardo Sepúlveda",
    position: "Defensa",
    number: 27,
    image: "/images/players/leonardo-sepulveda.png",
  },
  {
    name: "Raúl Martínez",
    position: "Defensa",
    number: 33,
    image: "/images/players/raul-martinez.png",
  },
  {
    name: "Erick Gutiérrez",
    position: "Mediocampista",
    number: 15,
    image: "/images/players/erick-gutierrez.png",
  },
  {
    name: "Omar Govea",
    position: "Mediocampista",
    number: 7,
    image: "/images/players/omar-govea.png",
  },
  {
    name: "Issac Brizuela",
    position: "Mediocampista",
    number: 11,
    image: "/images/players/issac-brizuela.png",
  },
  {
    name: "Luis Romo",
    position: "Mediocampista",
    number: 17,
    image: "/images/players/luis-romo.png",
  },
  {
    name: "Daniel Aguirre",
    position: "Mediocampista",
    number: 23,
    image: "/images/players/daniel-aguirre.png",
  },
  {
    name: "Rubén González",
    position: "Mediocampista",
    number: 28,
    image: "/images/players/ruben-gonzalez.png",
  },
  {
    name: "Javier Hernández",
    position: "Delantero",
    number: 14,
    image: "/images/players/javier-hernandez.png",
  },
  {
    name: "Alan Pulido",
    position: "Delantero",
    number: 9,
    image: "/images/players/alan-pulido.png",
  },
  {
    name: "Cade Cowell",
    position: "Delantero",
    number: 16,
    image: "/images/players/cade-cowell.png",
  },
  {
    name: "Roberto Alvarado",
    position: "Delantero",
    number: 25,
    image: "/images/players/roberto-alvarado.png",
  },
  {
    name: "Yael Padilla",
    position: "Delantero",
    number: 31,
    image: "/images/players/yael-padilla.png",
  },
  {
    name: "Armando González",
    position: "Delantero",
    number: 34,
    image: "/images/players/armando-gonzalez.png",
  },
  {
    name: "Teun Wilke",
    position: "Delantero",
    number: 35,
    image: "/images/players/teun-wilke.png",
  },
];
