import type { Player } from "@/types/player";

export const players: Player[] = [
  {
    name: "Blanca Félix",
    position: "Portero",
    number: 12,
    image: "/images/players/chivas-femenil/blanca-felix.png",
    stats: {
      appearances: 20,
      goals: 0,
      assists: 0,
      yellowCards: 1,
      redCards: 0,
      minutesPlayed: 1800,
    },
  },
  {
    name: "Celeste Espino",
    position: "Portero",
    number: 1,
    image: "/images/players/chivas-femenil/celeste-espino.png",
  },
  {
    name: "Araceli Torres",
    position: "Defensa",
    number: 26,
    image: "/images/players/chivas-femenil/araceli-torres.png",
  },
  {
    name: "Jaqueline Rodríguez",
    position: "Defensa",
    number: 2,
    image: "/images/players/chivas-femenil/jaqueline-rodriguez.png",
  },
  {
    name: "Damaris Godínez",
    position: "Defensa",
    number: 3,
    image: "/images/players/chivas-femenil/damaris-godinez.png",
  },
  {
    name: "Kinberly Guzmán",
    position: "Defensa",
    number: 4,
    image: "/images/players/chivas-femenil/kinberly-guzman.png",
  },
  {
    name: "Ana Camila Hernández",
    position: "Defensa",
    number: 6,
    image: "/images/players/chivas-femenil/anacamila-hernandez.png",
  },
  {
    name: "Carolina Jaramillo",
    position: "Mediocampista",
    number: 8,
    image: "/images/players/chivas-femenil/carolina-jaramillo.png",
  },
  {
    name: "Casandra Montero",
    position: "Mediocampista",
    number: 7,
    image: "/images/players/chivas-femenil/casandra-montero.png",
  },
  {
    name: "Yamile Franco",
    position: "Mediocampista",
    number: 11,
    image: "/images/players/chivas-femenil/yamile-franco.png",
  },
  {
    name: "Dana Sandoval",
    position: "Mediocampista",
    number: 13,
    image: "/images/players/chivas-femenil/dana-sandoval.png",
  },
  {
    name: "Joselyn De La Rosa",
    position: "Mediocampista",
    number: 14,
    image: "/images/players/chivas-femenil/joselyn-de-la-rosa.png",
  },
  {
    name: "Daniela Delgado",
    position: "Mediocampista",
    number: 19,
    image: "/images/players/chivas-femenil/daniela-delgado.png",
  },
  {
    name: "Ivonne González",
    position: "Mediocampista",
    number: 20,
    image: "/images/players/chivas-femenil/ivonne-gonzalez.png",
  },
  {
    name: "Alicia Cervantes",
    position: "Delantero",
    number: 24,
    image: "/images/players/chivas-femenil/alicia-cervantes.png",
  },
  {
    name: "Gabriela Valenzuela",
    position: "Delantero",
    number: 9,
    image: "/images/players/chivas-femenil/gabriela-valezuela.png",
  },
  {
    name: "Adriana Iturbide",
    position: "Delantero",
    number: 10,
    image: "/images/players/chivas-femenil/adriana-iturbide.png",
  },
  {
    name: "Montserrat Hernández",
    position: "Delantero",
    number: 18,
    image: "/images/players/chivas-femenil/montserrat-hernandez.png",
  },
  {
    name: "Viridiana Salazar",
    position: "Delantero",
    number: 30,
    image: "/images/players/chivas-femenil/viridiana-salazar.png",
  },
];
