import type { ScheduleMatch } from "@/types/schedule";

export const matches: ScheduleMatch[] = [
  {
    home: { name: "León", logo: "/images/teams/leon.svg" },
    away: {
      name: "Chivas",
      logo: "/images/teams/chivas.svg",
    },
    date: "Sábado / 19 Jul / 2025",
    time: "19:00",
    stadium: "Nou Camp",
    jornada: "J2",
  },
  {
    home: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    away: {
      name: "Atl. San Luis ",
      logo: "/images/teams/atletico-de-san-luis.png",
    },
    date: "Sábado / 26 Jul / 2025",
    time: "17:00",
    stadium: "Akron",
    jornada: "J3",
  },
  {
    home: { name: "Santos", logo: "/images/teams/santos.svg" },
    away: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    date: "Domingo / 10 Ago / 2025",
    time: "20:00",
    stadium: "TSM Corona",
    jornada: "J4",
  },
  {
    home: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    away: { name: "FC Juárez", logo: "/images/teams/juarez.svg" },
    date: "Sábado / 16 Ago / 2025",
    time: "17:00",
    stadium: "Akron",
    jornada: "J5",
  },
  {
    home: { name: "Xolos", logo: "/images/teams/xolos.svg" },
    away: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    date: "Sábado / 22 Ago / 2025",
    time: "21:00",
    stadium: "Caliente",
    jornada: "J6",
  },
  {
    home: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    away: { name: "Cruz Azul", logo: "/images/teams/cruz-azul.svg" },
    date: "Sábado / 30 Ago / 2025",
    time: "19:00",
    stadium: "Akron",
    jornada: "J7",
  },

  {
    home: { name: "América", logo: "/images/teams/america.svg" },
    away: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    date: "Viernes / 12 Sep / 2025",
    time: "19:00",
    stadium: "Cd. de los Deportes",
    jornada: "J8",
  },
  {
    home: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    away: { name: "Tigres", logo: "/images/teams/tigres.svg" },
    date: "Miércoles / 17 Sep / 2025",
    time: "19:00",
    stadium: "Akron",
    jornada: "J1",
  },
  {
    home: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    away: { name: "Toluca", logo: "/images/teams/toluca.svg" },
    date: "Sábado / 20 Sep / 2025",
    time: "19:00",
    stadium: "Akron",
    jornada: "J9",
  },
  {
    home: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    away: { name: "Necaxa", logo: "/images/teams/necaxa.svg" },
    date: "Martes / 23 Sep / 2025",
    time: "19:00",
    stadium: "Akron",
    jornada: "J10",
  },
  {
    home: { name: "Puebla", logo: "/images/teams/puebla.svg" },
    away: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    date: "Viernes / 26 Sep / 2025",
    time: "21:00",
    stadium: "Cuauhtémoc",
    jornada: "J11",
  },
  {
    home: { name: "Pumas", logo: "/images/teams/pumas.svg" },
    away: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    date: "Domingo / 05 Oct / 2025",
    time: "19:00",
    stadium: "Olímpico Universitario",
    jornada: "J12",
  },
  {
    home: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    away: { name: "Mazatlán", logo: "/images/teams/mazatlan.svg" },
    date: "Sábado / 18 Sep / 2025",
    time: "19:00",
    stadium: "Akron",
    jornada: "J13",
  },
  {
    home: { name: "Queretaro", logo: "/images/teams/queretaro.svg" },
    away: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    date: "Miércoles / 22 Oct / 2025",
    time: "19:00",
    stadium: "La Corregidora",
    jornada: "J14",
  },
  {
    home: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    away: { name: "Atlas", logo: "/images/teams/atlas.svg" },
    date: "Sábado / 25 Oct / 2025",
    time: "21:00",
    stadium: "Akron",
    jornada: "J15",
  },
  {
    home: { name: "Pachuca", logo: "/images/teams/pachuca.svg" },
    away: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    date: "Domingo / 02 Nov / 2025",
    time: "19:00",
    stadium: "Hidalgo",
    jornada: "J16",
  },
  {
    home: { name: "Chivas", logo: "/images/teams/chivas.svg" },
    away: { name: "Monterrey", logo: "/images/teams/monterrey.svg" },
    date: "Sábado / 08 Nov / 2025",
    time: "17:00",
    stadium: "Akron",
    jornada: "J17",
  },
];
